#!/usr/bin/perl

# Return a page of links to pages that are referenced but don't exist.

do "../common.perl";

%missing = ();
opendir PAGES, "$pagedir" or die "can't opendir $pagedir: $!";
foreach my $source
    (grep { $_ !~ m/^\./ && -r "$pagedir/$_" && -f "$pagedir/$_" }
          readdir PAGES) {
    # no lines that start with whitespace or comment (++) tag
    my $t = join '\n',
        (grep { ! m/^(\s+|\+\+)/ } (split '\n', page_text($source)));
    $t =~ s/\[\[.*?\]\]//go;                     # no explicit links
    $t =~ s/\b$interprefix:$wikilink\b//go;      # no interwiki links
    foreach
        (grep { !(-r "$pagedir/$_" && -f "$pagedir/$_") }
         ($t =~ m/\b$wikilink\b/go))
        { $missing{$_}{$source} = 1 };
};
closedir PAGES;

@missing = ();
foreach my $m (sort keys %missing) {
    @sources = ();
    foreach
        (sort keys %{$missing{$m}})
        { push @sources,
              "  <li>" . hyper($_, script_href("show", $_)) . "</li>" };

    push @missing,
        "<h2>" . hyper($m, script_href("edit", $m), "missing")
        . "</h2>\n<ul>\n"
        . (join "\n", @sources) . "\n</ul>";
}

$content = "<div class=\"missingpages\">\n"
    . (join "\n", @missing) . "\n</div>";

my $count = @missing;

findfooter();
validator();
generate_xhtml("Missing pages", "Referenced but missing pages ($count)", "no");
