#!/usr/bin/perl

do "../common.perl";

sub do_text_search {
    my @matches = filter_pages(sub { page_property($_, 'markup') =~ m/$page/i });
    gen_search_page("Pages mentioning $page",
                    "Pages mentioning <em>$page</em>", @matches);
}

sub do_name_search {
    my @matches = filter_pages(sub { m/$page/i });
    gen_search_page("Page names containing $page",
                    "Page names containing <em>$page</em>", @matches);
}

sub gen_search_page {
    my ($title, $heading, @matches) = @_;
    if (@matches) {
        $content  = "<ul>\n  <li>"
            .  (join "</li>\n  <li>",
                (map make_wiki_link($_), (sort @matches)))
            . "</li>\n</ul>";
    } else {
        $content  = "<p>No matches found.</p>";
    }
    findfooter();
    validator();
    generate_xhtml($title, $heading, "no");
}

($type, $page) = parse_http_data($ENV{'QUERY_STRING'});
if ($type eq "name") {
    do_name_search();
} elsif ($type eq "text") {
    do_text_search();
} else {
    gen_search_page("Unknown search", "Unknown search", ());
}
