#!/usr/bin/perl

### Read in common code ###
do "../common.perl";

### Get rendering code ###
do "../render.perl";

# do_xxx needs to do something like this:
# $content = ...
# @footerlines  = ...
# generate_xhtml($title, $page_heading);
sub do_show {
    my $robots = "";
    $_ = page_property($page, 'markup');

    # if not editable and non-existent, return a 404 Not found error page.
    # This is mostly so spiders know that the page really doesn't exist.
    unless ($_) {
        if ($editable) {
            $_ = "$page doesn't exist. Why not create it by editing the text of this page?\n";
        } else {
            $_ = "Sorry, that page doesn't exist.\n";
            $http_response_headers{'Status'} = "404 Not found";
        }
        $robots = "no";
    }

    render_page($robots);
}

redirect_to_canonical_uri();
do_show();
