#!/usr/bin/perl -w

# $Id$

do "common.pl";

sub filter_pages {
    my ($dir, $pred) = @_;
    opendir PAGES, "$dir" or die "can't opendir $dir: $!";
    my @matches = grep { ! m/^\./ && -r "$dir/$_" && -f "$dir/$_"
                         && &$pred() } readdir PAGES;
    closedir PAGES;
    return @matches;
}

sub do_text_search {
    my @matches = filter_pages($pagedir, sub { page_text($_) =~ m/$page/i });
    gen_search_page("Pages mentioning $page",
                    "Pages mentioning <em>$page</em>", @matches);
}

sub do_name_search {
    my @matches = filter_pages($pagedir, sub { m/$page/i });
    gen_search_page("Page names containing $page",
                    "Page names containing <em>$page</em>", @matches);
}

sub gen_search_page {
    my ($title, $heading, @matches) = @_;
    if (@matches) {
        $content  = "<ul>\n"
            .  (join "\n", (map { "  <li>" . make_wiki_link($_) . "</li>" }
                                (sort @matches)))
            . "\n</ul>\n";
    } else {
        $content  = "<p>No matches found.</p>\n";
    }
    findfooter();
    validator();
    generate_xhtml($title, $heading, "no");
}

($type, $page) = parse_http_data($ENV{'QUERY_STRING'});
if ($type eq "name") {
    do_name_search();
} elsif ($type eq "text") {
    do_text_search();
} else {
    gen_search_page("Unknown search", "Unknown search", ());
}
